port06<-read.xlsx("PortSales2006.xlsx",1)
names(port06)<-c("country","vinho","year","litros","euros", "euro.litro")
port13<-read.xlsx("PortSales2013.xlsx",1)
names(port13)<-c("country","vinho","year","litros","euros", "euro.litro")
mrg<-merge(port13,port06,by="country")
mrg<-select(mrg,country,euros.y,euros.x)
mrg<-mutate(mrg,percent.change=round((((euros.x-euros.y)/euros.x)*100),digits=2))
mrg<-arrange(mrg,desc(percent.change))
names(mrg)<-c("Country","2006 €","2013 €","Change %")
port<-write.csv(mrg,"porttable.csv")
